apiVersion: v1
kind: Namespace
metadata:
  name: minecraft

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft
data:
  EULA: "TRUE"
  TYPE: "PAPER"
  VERSION: "1.21.1"
  MEMORY: "1G"
  MOTD: "Kanstantsin Nechyparenka nechypak - Ops4"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: minecraft

  template:
    metadata:
      labels:
        app: minecraft

    spec:
      imagePullSecrets:
        - name: ecr-creds

      containers:
        - name: minecraft
          image: "339712937184.dkr.ecr.us-east-1.amazonaws.com/ops3-minecraft-lab:mc-java21-v1"
          imagePullPolicy: Always

          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP

          envFrom:
            - configMapRef:
                name: minecraft-config

          volumeMounts:
            - name: minecraft-data
              mountPath: /data

          startupProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 6

          resources:
            requests:
              cpu: "500m"
              memory: "1536Mi"
            limits:
              cpu: "1500m"
              memory: "2Gi"

      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: minecraft-data

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  type: LoadBalancer

  selector:
    app: minecraft

  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565